apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eshop
  namespace: argocd
spec:
  description: eShopOnContainers microservices platform
  sourceRepos:
    - https://github.com/GABRIELS562/*
  destinations:
    - namespace: eshop
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
