apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: otlp-grpc
      port: {{ .Values.service.otlpGrpcPort }}
      targetPort: {{ .Values.service.otlpGrpcPort }}
      protocol: TCP
    - name: otlp-http
      port: {{ .Values.service.otlpHttpPort }}
      targetPort: {{ .Values.service.otlpHttpPort }}
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
      protocol: TCP
  selector:
    {{- include "otel-collector.selectorLabels" . | nindent 4 }}
