apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    app: rabbitmq
    env: production
    team: platform
    version: "3.12"
type: Opaque
stringData:
  username: "eshop"
  password: "eshop-rabbitmq-2026"
  erlang-cookie: "ESHOPPLATFORMERLANGCOOKIE2026"
  connection-string: "amqp://eshop:eshop-rabbitmq-2026@rabbitmq:5672/eshop"
