apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webhook-api
  namespace: argocd
  labels:
    app: webhook-api
    env: production
    team: platform
spec:
  project: eshop
  source:
    repoURL: https://github.com/GABRIELS562/eshop-platform-infra
    targetRevision: main
    path: helm-charts/webhook-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: eshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/metrics
