{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "ordering-signalr.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ordering-signalr.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ include "ordering-signalr.fullname" . }}-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "ordering-signalr.labels" . | nindent 10 }}
  data:
    - secretKey: IDENTITY_URL
      remoteRef:
        key: {{ .Values.vault.secretPath }}
        property: IDENTITY_URL
  dataFrom:
    - extract:
        key: secret/eshop/global
{{- end }}
